#####################################
## Common
#####################################
server:
  port: 9010

#####################################
## SPRING
#####################################
spring:
  application:
    name: frs-console
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: never

#####################################
## ACTUATOR
#####################################
management:
  endpoints:
    web:
      base-path: "/frs/v1/"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowedHeaders: "*"
        allowCredentials: true
      exposure:
        include: "*"
  metrics:
    enable:
      process:
        files: false
        cpu: false
      jvm:
        buffer: false
        classes: false
      hikaricp: false
      system: false
      jdbc: false
      logback: false
      cache: false
    web:
      server:
        request:
          autotime:
            enabled: true
    tags:
      application: ${spring.application.name}


---
spring:
  profiles:
    - dev

---
spring:
  profiles:
    - preprod

---
spring:
  profiles:
    - prod
