#####################################
## Common
#####################################
server:
  port: 9010

#####################################
## SPRING
#####################################
spring:
  application:
    name: frs-console
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: never
  r2dbc:
    url: ${FRS_R2DBC_POSTGRES_URL:}
    username: ${FRS_R2DBC_POSTGRES_USERNAME:}
    password: ${FRS_R2DBC_POSTGRES_PASSWORD:}
    pool:
      enabled: true
      initial-size: 1
      max-size: 10
      max-idle-time: 10m
      validation-query: SELECT 1

#####################################
## ACTUATOR
#####################################
management:
  endpoints:
    web:
      base-path: "/frs/v1/"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowedHeaders: "*"
        allowCredentials: true
      exposure:
        include: "*"
  metrics:
    enable:
      process:
        files: false
        cpu: false
      jvm:
        buffer: false
        classes: false
      hikaricp: false
      system: false
      jdbc: false
      logback: false
      cache: false
    web:
      server:
        request:
          autotime:
            enabled: true
    tags:
      application: ${spring.application.name}


---
spring:
  profiles:
    - local

application:
  version: 0.0.1-TEST

---
spring:
  profiles:
    - dev

---
spring:
  profiles:
    - prod
