dist: trusty
language: java
jdk:
  - openjdk11

cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  ssh_known_hosts:
    - 193.123.236.99

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out id_rsa -d

script: "./gradlew :frs-app-console:build"

before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 ./id_rsa
  - ssh-add ./id_rsa
  - rsync -r $HOME/provision/frs-pvs/deploy/ ubuntu@193.123.236.99:deploy/

deploy:
  skip_cleanup: true
  provider: script
  script: "./gradlew :frs-app-console:jib"

notifications:
  email:
    recipients:
      - ballgaveship@gmail.com