dist: trusty
language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew

script: "./gradlew :frs-app-console:build"

deploy:
  provider: script
  script: "./gradlew :frs-app-console:jib"