###
GET http://localhost:9080/dam/v1/assets?q=O
Content-Type: application/json


###
GET http://localhost:9080/v1/assets/1587532126ABbq
Content-Type: application/json


###
GET http://localhost:9080/v1/assets?limit=20&q=&status=isVisible:true
Content-Type: application/json


###
GET http://localhost:9080/v1/assets?jobId=1587431215m5E1&offset=0&limit=99999
Content-Type: application/json


### videoId -> packageId
###
GET http://localhost:9080/v1/assets?limit=99999&packageId=1587554744y7rV
Content-Type: application/json


###
GET http://localhost:9080/v1/packages/1587554744y7rV
Content-Type: application/json


###
GET http://localhost:9080/v1/packages?type=VIDEO&limit=20&q=&status=isVisible:true
Content-Type: application/json


###
GET http://localhost:9080/v1/packages?type=VIDEO&assetId=1587532126ABbq&limit=99999
Content-Type: application/json


###
GET http://localhost:9080/v1/assets/test
Content-Type: application/json



###############################
###### ASSET LISTING (isHidden=true는 제외가 Default 조건)
###
GET http://localhost:9080/v1/assets?limit=20&q=
Content-Type: application/json


###### ASSET DETAIL
###
GET http://localhost:9080/v1/assets/1587532126ABbq
Content-Type: application/json


###### ASSET SEARCH
### Quick Search (Name, Id, CreatedByUsername, CreateByName, JobId, Tags)
GET http://localhost:9080/v1/assets?limit=20&q=TEST


### Advance Search (status 검색)
GET http://localhost:9080/v1/assets?limit=20&status=hasDubbing:false&tags=


### Advance Search (sysAttr 검색)
GET http://localhost:9080/v1/assets?limit=20&sysAttr=jobId:1588495912dyrX&tags=


### Advance Search (status, sysAttr 검색)
GET http://localhost:9080/v1/assets?limit=20&sysAttr=jobId:1588495912dyrX,status:ACTIVE&status=isLocked:false,hasDubbing:true&tags=


### Another Search (packageId 검색, mapping Table 검색)
GET http://localhost:9080/v1/assets?limit=20&packageId=1588495912dyrX&tags=


###############################
###### Package LISTING (isHidden=true는 제외가 Default 조건)
###
GET http://localhost:9080/v1/packages?type=VIDEO&limit=20&q=
Content-Type: application/json


###### Package DETAIL
###
GET http://localhost:9080/v1/packages/1587532126ABbq
Content-Type: application/json


###### Package SEARCH
### Quick Search (Name, Id, CreatedByUsername, CreateByName, JobId, Tags)
GET http://localhost:9080/v1/packages?type=VIDEO&limit=20&q=TEST


### Advance Search (status 검색)
GET http://localhost:9080/v1/packages?type=VIDEO&limit=20&status=hasDubbing:false&tags=


### Advance Search (sysAttr 검색)
GET http://localhost:9080/v1/packages?type=VIDEO&limit=20&sysAttr=status:ACTIVE&tags=


### Advance Search (status, sysAttr 검색)
GET http://localhost:9080/v1/packages?type=VIDEO&limit=20&sysAttr=status:ACTIVE&status=hasCaption:false,hasDubbing:true&tags=


### Another Search (assetId 검색, mapping Table 검색)
GET http://localhost:9080/v1/packages?limit=20&assetId=1588495912dyrX&tags=


### Another Search (assetId 검색, mapping Table 검색)
GET http://localhost:9080/dam/v1/users?searchConditions=v1