version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  frs_server:
    container_name: frs_server
    image: docker.pkg.github.com/ballgaveship/food_reservation_system_server/frs-admin:1.0.0
    ports:
      - "9010:9010"
