---
profiles: local
version: 1.0.0-SNAPSHOT
docker:
  registryHost: 193.123.236.99:5000/frs-admin

---
profiles: dev
version: 1.0.0-SNAPSHOT
docker:
  registryHost: 193.123.236.99:5000/frs-admin

---
profiles: preprod
version: 1.0.0-SNAPSHOT
docker:
  registryHost: 193.123.236.99:5000/frs-admin

---
profiles: prod
version: 1.0.0-SNAPSHOT
docker:
  registryHost: 193.123.236.99:5000/frs-admin
